---
name: "Adrián"
surname: "Cidre González"
position: "Forestry Researcher"
address: "Gesplan S.A. | University of Córdoba"
profilepic: "img/me-tenerife.jpg"
email: "adrian.cidre@gmail.com"
www: "adrian-cidre.com"

#twitter: mariecurie
github: Cidree
linkedin: adrian-cidre
date: "June 2025"
headcolor: 990000
aboutme: "I have a strong background in forest sciences with special interest on remote sensing and data science. I have honed my skills on remote sensing, applications development, spatial data analysis, and data science applied to forestry. I am eager to apply my skills and enthusiasm in a dynamic and challenging environment, where I can make a meaningful contribution and foster growth. In my toolkit I include R, Python, Google Earth Engine, Shiny, Quarto, DuckDB, among others."
docname: CV
language: en
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  
  "University of Córdoba", "2024-Current", "PhD in Biosciences and Agri-food Sciences", "Córdoba, Spain",
  
  "University of Córdoba", "2022-2023", "Master in Geomatics, Remote Sensing and Spatial Models Applied to Forest Management", "Córdoba, Spain",
  
  
  "National University of Distance Education", "2022-2023", "Expert Title in Advance Applied Statistics", "Online",
  
  "University of Santiago de Compostela", "2018-2022", "Bachelor in Forestry and Landscape Engineering", "Lugo, Spain",
  
  "IES Plurilingüe San Rosendo", "2016-2018", "Certificate of Higher Education in Forestry", "Mondoñedo, Spain",
) |> 
  detailed_entries(Degree, Year, Institution, Where)
```

# Work Experience

```{r}
tribble(
    ~title, ~unit, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
    
    # Gesplan -----
    "Forest Engineer", "Gesplan S.A. - Canary pine silviculture", "January", 2025, "--> Present", NA, "Tenerife - Spain",  NA,
    
    # UCO ----
    "Forestry Engineer - Geomatics", "University of Córdoba - Bio+A Málaga Project", "September", 2024, "--> December 2024", NA, "Córdoba - Spain", NA,
    
    "Forestry Engineer - Geomatics", "University of Córdoba - LIFE FAGESOS", "September", 2022, "--> December", 2023, "Córdoba - Spain", NA,
    
    # Teaching Udemy ----
    "R Instructor", "Udemy - https://adrian-cidre.com/courses.html", "July", 2023, "--> Present", NA, "Online", NA,
    
    # FIREFIGHTING ----
    "Wildland Firefighter", "Repoblación y Bosquetes, S.A. - Aerial Squad Technician", "Summer", 2022, NA, NA, "Galicia - Spain", NA,
    
    "Wildland Firefighter", "Repoblación y Bosquetes, S.A. - Aerial Squad Crew Leader", "Summer", 2021, NA, NA, "Galicia - Spain", NA,
    
    "Wildland Firefighter", "Demontes, S.L. - Aerial Squad Crew Member", "Summer", 2020, NA, NA, "Galicia - Spain", NA,
    
    "Wildland Firefighter", "Demontes, S.L. - Aerial Squad Crew Member", "Summer", 2019, NA, NA, "Galicia - Spain", NA,
    
    "Wildland Firefighter", "SEAGA, S.A. - Ground Brigade Crew Member", "Summer", 2018, NA, NA, "Galicia - Spain", NA,
    
    "Forestry Technician", "Servitec Medioambiente, S.L. - Forest Inventory", "March", 2018, "--> June", 2018, "Galicia - Spain", NA,
    
    
) |> 
  detailed_entries(
    with  = title,
    what  = unit,
    why   = detail,
    when  = glue::glue("{startMonth} {startYear}  {endMonth} {endYear}", .na = ""),
    where = where
  )
```

\newpage

# Mobility

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  
  "Norwegian University of Life Sciences", "March 2024 -> May 2024", "Erasmus+ Internship - Research Assistant", "Ås, Norway",
  
  "Mendel University in Brno", "March 2022 -> May 2022", "Erasmus+ Internship - Forestry", "Brno, Czech Republic",
  
  "University of Córdoba", "September 2021 -> February 2022", "SICUE - Study Mobility", "Córdoba, Spain",
  
  "University of Eastern Finland", "January 2021 -> June 2021", "Erasmus+ - Study Mobility", "Joensuu, Finland"
) |> 
  detailed_entries(Degree, Year, Institution, Where)
```



# Skills  

```{r}
tribble(
    ~area, ~skills,
    "Programming Languages", 
    "R (top skill), 
    Python",
    "Expertise",
    "Geospatial Data,
    Remote Sensing,
    Data Analysis,
    Data Science,
    Machine Learning,
    Deep Learning,
    Computer Vision,
    Shiny Applications",
    
    "Toolkit", "R & Python, Shiny, Quarto, Google Earth Engine, QGIS, Orfeo Toolbox, PostgreSQL & PostGIS, DuckDB, HTML & CSS, MongoDB, Git & GitHub, Docker"
) |> 
  detailed_entries(
    with = area,
    what = skills
)
```

# Projects

```{r}
tribble(
    ~area, ~accomplishment, ~year, ~where, ~detail,
    

    
    "A Combined Habitat Suitability and Process-Based Model to Assess the Suitable Habitat and Virulence Potential of Phytophthora cinnamomi in Mediterranean Forest Ecosystems", "Universidad de Córdoba - https://doi.org/10.1016/j.ecolmodel.2025.111115", 2023, "Master Thesis - Published", NA,
    
    "LIFE-FAGESOS WP2 --- FAGESOS-GIS: Creation of a GIS-based service platform for disease impact and risk assessment", "University of Córdoba", 2023, "LIFE Project", NA,
    
    "Fragmentation and and connectivity in dehesa ecosystems associated to Cerambycids dispersion in Sierra Morena: A Graph-Theory approach", "Universidad de Córdoba - https://doi.org/10.3390/f15040648", 2022, "Bachelor Thesis - Published", NA
    
) |> 
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```



# R packages

```{r}
tribble(
    ~package, ~description,
    "duckspatial", "A small wrapper around reading/writting functions to DuckDB database in R.",
    "forestdata", "It includes functions to retrieve forestry and land cover data from various sources.",
    "OTBsegm", "An R package for unsupervised segmentation algorithms included in Orfeo ToolBox",
    "rpostgis", "Interface between R and PostGIS-enabled PostgreSQL databses.",
    "silviculture", "An R package to accelerate the analysis of forest inventory data."
) |> 
  detailed_entries(
    with = package,
    what = description
)
```

\newpage

# Complementary Edutation  

```{r}
tribble(
    ~area, ~detail,
    
    # Business Science University
    "Business Science University", "Data Science for Business Part 1", 
    "Business Science University", "Data Science for Business Part 2", 
    "Business Science University", "Shiny Web Applications Part 1", 
    "Business Science University", "Shiny Web Applications Part 2", 
    "Business Science University", "High Performance Time Series", 
    "Business Science University", "", 
    
    # Udemy (R)
    "Formation in Udemy", "Machine Learning A-Z: AI Python & R + ChatGPT Prize (2024)",
    "Formation in Udemy", "R Shiny Interactive Web Apps - Next Level Data Visualization", 
    "Formation in Udemy", "Artificial Intelligence Bootcamp in R Programming", 
    "Formation in Udemy", "Survival Analysis in R",
    "Formation in Udemy", "Spatial Data Analysis with R and QGIS",
    "Formation in Udemy", "Learn ggplot2 in R for Data Visualization",
    "Formation in Udemy", "Curso avanzado de estadística multivariante con R y Python", 
    "Formation in Udemy", "Ecology in R", 
    "Formation in Udemy", "Mastering Data Visualization: Theory and Foundations", 
    "Formation in Udemy", "The Complete SQL Bootcamp: Go from Zero to Hero", 
    "Formation in Udemy", "Introduction to Spatial Databases with PostGIS and QGIS 3", 
    "Formation in Udemy", "Python for Data Science and Machine Learning Bootcamp", 
    "Formation in Udemy", "Google Earth Engine y Machine Learning: de cero a experto",
    "Formation in Udemy", "CSS - The Complete Guide 2024",
    "Formation in Udemy", "YOLOv7, YOLOv8, YOLOv9 - Deep Learning Course",
    "Formation in Udemy", "GitHub Actions - The Complete Guide",
    "Formation in Udemy", "",
    
    # Other courses
    "Forestry Formation", "Inventarios Naturales de Flora y Fauna (75 hours)",
    "Forestry Formation", "Incendios Forestales - Efectos Medioambientales (120 hours)",
    "Forestry Formation", "Restauración ecológica de ecosistemas forestales (50 hours)",
    "Forestry Formation", "Sistemas de Información Geográfica con QGIS (60 hours)",
    "Forestry Formation", "Incendios Forestales - Efectos Medioambientales (120 hours)",

) |> 
   detailed_entries(
    with = area,
    why = detail
  )
```













